
// ============================================================================
// 🎉 NEW TEMPLATES ADDED - 45 TOTAL
// ============================================================================
// Generated by multi-agent swarm competing for jlopez's attention! 💪
//
// INTEGRATION INSTRUCTIONS:
// 1. Copy the templates below
// 2. Paste them at the END of the templates array in src/data/templates.ts
// 3. Make sure to add a comma after the last existing template
// 4. Update category counts in src/data/categories.ts
//
// BREAKDOWN:
// - Writing & Content: 15 new templates
// - Coding & Development: 15 new templates  
// - Productivity & Planning: 10 new templates
// ============================================================================



// ========== WRITING & CONTENT TEMPLATES ==========
  {
    id: 'cold-outreach-email',
    category: 'writing',
    title: 'Cold Outreach Email',
    icon: 'Envelope',
    description: `Craft compelling cold emails that get responses using proven frameworks`,
    fields: [
      {
            "name": "recipient_role",
            "label": "Recipient Role",
            "type": "text",
            "placeholder": "e.g., Marketing Director"
      },
      {
            "name": "product_service",
            "label": "Your Product/Service",
            "type": "text",
            "placeholder": "What are you offering?"
      },
      {
            "name": "value_prop",
            "label": "Key Value Proposition",
            "type": "text",
            "placeholder": "Main benefit"
      },
      {
            "name": "tone",
            "label": "Tone",
            "type": "select",
            "options": [
                  "Professional",
                  "Casual",
                  "Friendly",
                  "Direct"
            ]
      }
],
    promptTemplate: `Write a cold outreach email to a {recipient_role} about {product_service}.

Key value proposition: {value_prop}
Tone: {tone}

Structure:
1. **Subject Line**: Attention-grabbing, specific, under 50 characters
2. **Opening**: Personalized observation or compliment (research-based)
3. **Problem**: Identify a pain point they likely face
4. **Solution**: How {product_service} solves it (focus on outcomes, not features)
5. **CTA**: Single, clear next step (15-min call, demo, resource)

Keep it under 150 words. No fluff, no jargon.`
  },
  {
    id: 'resume-bullet-points',
    category: 'writing',
    title: 'Resume Bullet Points',
    icon: 'ListBullets',
    description: `Transform job responsibilities into achievement-focused resume bullets`,
    fields: [
      {
            "name": "job_title",
            "label": "Job Title",
            "type": "text",
            "placeholder": "e.g., Product Manager"
      },
      {
            "name": "responsibilities",
            "label": "Key Responsibilities",
            "type": "textarea",
            "placeholder": "List what you did..."
      },
      {
            "name": "achievements",
            "label": "Measurable Results",
            "type": "textarea",
            "placeholder": "Any metrics or outcomes?"
      }
],
    promptTemplate: `Transform these job responsibilities into powerful resume bullet points for a {job_title} role.

Responsibilities:
{responsibilities}

Achievements/Metrics:
{achievements}

Use the XYZ formula: "Accomplished [X] as measured by [Y], by doing [Z]"

Requirements:
- Start with strong action verbs (Led, Drove, Increased, Reduced, Launched)
- Include quantifiable metrics (%, $, time saved, users impacted)
- Focus on impact and results, not just tasks
- Keep each bullet to 1-2 lines
- Generate 5-7 bullets`
  },
  {
    id: 'cover-letter-generator',
    category: 'writing',
    title: 'Cover Letter Generator',
    icon: 'FileText',
    description: `Write a standout cover letter that grabs recruiter attention`,
    fields: [
      {
            "name": "job_title",
            "label": "Job Title",
            "type": "text",
            "placeholder": "e.g., Senior Software Engineer"
      },
      {
            "name": "company_name",
            "label": "Company Name",
            "type": "text"
      },
      {
            "name": "key_skills",
            "label": "Your Key Skills",
            "type": "textarea",
            "placeholder": "List 3-5 relevant skills"
      },
      {
            "name": "why_company",
            "label": "Why This Company?",
            "type": "textarea",
            "placeholder": "What excites you about them?"
      }
],
    promptTemplate: `Write a cover letter for the {job_title} position at {company_name}.

My key skills: {key_skills}
Why I'm interested: {why_company}

Structure:
1. **Opening Hook**: Don't say "I am writing to apply." Start with why you admire {company_name} specifically (reference a recent product launch, mission, or value)
2. **The Match**: Connect 2-3 of my skills directly to the job requirements. Use specific examples
3. **Culture Fit**: Explain why I align with their values/mission
4. **Closing CTA**: Confidently request an interview

Tone: Enthusiastic but professional. Show personality.
Length: 250-350 words.`
  },
  {
    id: 'press-release-writer',
    category: 'writing',
    title: 'Press Release',
    icon: 'Newspaper',
    description: `Create newsworthy press releases that media outlets will publish`,
    fields: [
      {
            "name": "announcement",
            "label": "What's the News?",
            "type": "text",
            "placeholder": "Product launch, funding, partnership, etc."
      },
      {
            "name": "company_name",
            "label": "Company Name",
            "type": "text"
      },
      {
            "name": "key_details",
            "label": "Key Details",
            "type": "textarea",
            "placeholder": "Who, what, when, where, why"
      },
      {
            "name": "quote",
            "label": "Executive Quote",
            "type": "textarea",
            "placeholder": "Quote from CEO/founder"
      }
],
    promptTemplate: `Write a press release for {company_name} announcing: {announcement}

Key details: {key_details}
Executive quote to include: {quote}

Follow AP Style press release format:
1. **Headline**: Newsworthy, under 10 words
2. **Subheadline**: Expand on the headline
3. **Dateline**: [CITY, State, Date]
4. **Lead Paragraph**: Answer who, what, when, where, why in 2-3 sentences
5. **Body**: Expand with context, significance, and the executive quote
6. **Boilerplate**: 2-3 sentence company description
7. **Contact Info**: Media contact details

Tone: Objective, newsworthy, third-person. Avoid marketing fluff.`
  },
  {
    id: 'email-newsletter',
    category: 'writing',
    title: 'Email Newsletter',
    icon: 'EnvelopeOpen',
    description: `Design engaging email newsletters that drive opens and clicks`,
    fields: [
      {
            "name": "topic",
            "label": "Newsletter Topic",
            "type": "text",
            "placeholder": "This week's theme"
      },
      {
            "name": "audience",
            "label": "Target Audience",
            "type": "text",
            "placeholder": "Who are your subscribers?"
      },
      {
            "name": "cta_goal",
            "label": "Call-to-Action Goal",
            "type": "text",
            "placeholder": "What should readers do?"
      }
],
    promptTemplate: `Create an email newsletter about {topic} for {audience}.

Primary CTA goal: {cta_goal}

Structure:
1. **Subject Line**: Curiosity-driven or benefit-focused (under 50 chars)
2. **Preheader**: Expand on subject (40-100 chars)
3. **Opening**: Personal greeting + hook (why this matters now)
4. **Main Content**: 3 short sections with subheadings:
   - Insight/Story
   - Actionable tip
   - Resource/Link
5. **CTA**: Clear button text for {cta_goal}
6. **P.S.**: Personal note or teaser for next week

Tone: Conversational, like an email from a friend. Use "you" language.
Length: 300-500 words.`
  },
  {
    id: 'case-study-writer',
    category: 'writing',
    title: 'Case Study',
    icon: 'ChartLineUp',
    description: `Write compelling case studies that showcase customer success`,
    fields: [
      {
            "name": "customer_name",
            "label": "Customer/Company",
            "type": "text"
      },
      {
            "name": "problem",
            "label": "Problem They Faced",
            "type": "textarea"
      },
      {
            "name": "solution",
            "label": "Your Solution",
            "type": "textarea"
      },
      {
            "name": "results",
            "label": "Measurable Results",
            "type": "textarea",
            "placeholder": "Metrics, ROI, outcomes"
      }
],
    promptTemplate: `Write a case study featuring {customer_name}.

Problem: {problem}
Solution: {solution}
Results: {results}

Use the Problem-Solution-Results framework:

1. **Title**: "[Customer] Achieves [Specific Result] with [Your Product]"
2. **Executive Summary**: 2-3 sentence overview
3. **The Challenge**: Describe {problem} with emotional impact
4. **The Solution**: How {solution} was implemented (include specific features/approach)
5. **The Results**: Highlight {results} with bold metrics and quotes
6. **Conclusion**: Key takeaway and CTA

Include:
- Pull quotes from the customer
- Specific numbers and percentages
- Before/after comparison
- Visual data points

Tone: Professional storytelling. Make the customer the hero.
Length: 600-800 words.`
  },
  {
    id: 'linkedin-thought-leadership',
    category: 'writing',
    title: 'LinkedIn Thought Leadership',
    icon: 'LinkedinLogo',
    description: `Write viral LinkedIn posts that position you as an industry expert`,
    fields: [
      {
            "name": "topic",
            "label": "Topic/Insight",
            "type": "text",
            "placeholder": "Your hot take or lesson"
      },
      {
            "name": "industry",
            "label": "Industry",
            "type": "text",
            "placeholder": "Your field"
      },
      {
            "name": "post_type",
            "label": "Post Type",
            "type": "select",
            "options": [
                  "Story",
                  "Listicle",
                  "Contrarian Take",
                  "Lesson Learned"
            ]
      }
],
    promptTemplate: `Write a LinkedIn post about {topic} in the {industry} industry.

Post type: {post_type}

Use the "Broetry" format (short sentences, lots of white space):

Structure:
1. **Hook**: Controversial statement or surprising fact (1-2 lines)
2. **The Myth**: "Most people think X..." (1 line)
3. **The Reality**: "But actually, Y..." (1-2 lines)
4. **The Story/Evidence**: Personal anecdote or data (3-5 short paragraphs)
5. **The Lesson**: Key takeaway (1-2 lines)
6. **Engagement Question**: Ask readers for their opinion

Formatting:
- Max 3-4 words per line
- Use line breaks liberally
- No hashtags in body (add 3-5 at the end)
- Include one emoji maximum

Tone: Authentic, confident, conversational. Avoid corporate speak.
Length: 150-200 words.`
  },
  {
    id: 'video-script-writer',
    category: 'writing',
    title: 'Video Script',
    icon: 'VideoCamera',
    description: `Script engaging videos for YouTube, TikTok, or Instagram`,
    fields: [
      {
            "name": "video_topic",
            "label": "Video Topic",
            "type": "text"
      },
      {
            "name": "platform",
            "label": "Platform",
            "type": "select",
            "options": [
                  "YouTube",
                  "TikTok",
                  "Instagram Reels",
                  "LinkedIn"
            ]
      },
      {
            "name": "video_length",
            "label": "Target Length",
            "type": "select",
            "options": [
                  "30 seconds",
                  "60 seconds",
                  "3-5 minutes",
                  "10+ minutes"
            ]
      },
      {
            "name": "cta",
            "label": "Call-to-Action",
            "type": "text",
            "placeholder": "Subscribe, visit website, etc."
      }
],
    promptTemplate: `Write a video script about {video_topic} for {platform}.

Target length: {video_length}
CTA: {cta}

Script structure:

**[0-5 seconds] HOOK:**
- Shocking statement, question, or visual that stops the scroll
- Example: "I lost $10K before I learned this..."

**[5-15 seconds] PROMISE:**
- "In this video, you'll learn exactly how to..."
- Set clear expectations

**[15-30 seconds] CREDIBILITY:**
- "I've [achievement/experience]..."
- Build trust quickly

**[Main Content]:**
- Break into 3-5 clear points
- Use B-roll suggestions [in brackets]
- Include on-screen text cues
- Keep energy high

**[Final 10 seconds] CTA:**
- Reinforce {cta}
- Create urgency or FOMO

Include:
- [Camera angles]
- [Visual cues]
- Timing markers
- Emphasis on KEY WORDS

Tone: Energetic, authentic, conversational.`
  },
  {
    id: 'podcast-episode-outline',
    category: 'writing',
    title: 'Podcast Episode Outline',
    icon: 'Microphone',
    description: `Structure engaging podcast episodes with clear segments and talking points`,
    fields: [
      {
            "name": "episode_topic",
            "label": "Episode Topic",
            "type": "text"
      },
      {
            "name": "guest_name",
            "label": "Guest Name (if applicable)",
            "type": "text",
            "placeholder": "Leave blank for solo episode"
      },
      {
            "name": "key_points",
            "label": "Key Points to Cover",
            "type": "textarea"
      },
      {
            "name": "episode_length",
            "label": "Target Length",
            "type": "select",
            "options": [
                  "15-20 min",
                  "30-45 min",
                  "60+ min"
            ]
      }
],
    promptTemplate: `Create a podcast episode outline for: {episode_topic}

Guest: {guest_name}
Key points: {key_points}
Target length: {episode_length}

Outline structure:

**[0-2 min] COLD OPEN:**
- Teaser: Most compelling moment from the episode
- Hook question or statement

**[2-5 min] INTRO:**
- Welcome + episode number
- Introduce {guest_name} (if applicable)
- Why this topic matters now
- What listeners will learn

**[Main Content - Segment by segment]:**
For each key point from {key_points}, create:
- Segment title
- Discussion questions (3-5 per segment)
- Potential stories/examples
- Transition to next segment

**[Final 5 min] WRAP-UP:**
- Recap key takeaways (3 bullets)
- Guest's final advice/CTA
- Sponsor message (if applicable)
- Preview next episode
- Where to find guest/resources

Include:
- Timestamp estimates
- Ad break placements
- Listener engagement prompts
- Show notes outline`
  },
  {
    id: 'advertisement-copy',
    category: 'writing',
    title: 'Advertisement Copy',
    icon: 'Megaphone',
    description: `Write high-converting ad copy for Facebook, Google, or LinkedIn`,
    fields: [
      {
            "name": "product_service",
            "label": "Product/Service",
            "type": "text"
      },
      {
            "name": "target_audience",
            "label": "Target Audience",
            "type": "text",
            "placeholder": "Who are you targeting?"
      },
      {
            "name": "platform",
            "label": "Ad Platform",
            "type": "select",
            "options": [
                  "Facebook/Instagram",
                  "Google Search",
                  "LinkedIn",
                  "TikTok"
            ]
      },
      {
            "name": "goal",
            "label": "Campaign Goal",
            "type": "select",
            "options": [
                  "Awareness",
                  "Leads",
                  "Sales",
                  "App Installs"
            ]
      }
],
    promptTemplate: `Write ad copy for {product_service} targeting {target_audience} on {platform}.

Campaign goal: {goal}

Create 3 variations:

**VARIATION 1: Problem-Focused**
- Headline: Call out the pain point (40 chars max)
- Body: Agitate the problem, introduce solution
- CTA: Clear action button

**VARIATION 2: Benefit-Focused**
- Headline: Lead with the transformation (40 chars max)
- Body: Paint the "after" picture
- CTA: Outcome-driven

**VARIATION 3: Urgency/Scarcity**
- Headline: Time-sensitive offer (40 chars max)
- Body: What they'll miss out on
- CTA: FOMO-driven

For each variation include:
- Primary text (125 chars for {platform})
- Headline
- Description (if applicable)
- CTA button text
- Image/video suggestions

Follow {platform} best practices and character limits.`
  },
  {
    id: 'creative-story-ideas',
    category: 'writing',
    title: 'Creative Story Ideas',
    icon: 'Lightbulb',
    description: `Generate unique story concepts for fiction, screenplays, or content`,
    fields: [
      {
            "name": "genre",
            "label": "Genre",
            "type": "select",
            "options": [
                  "Sci-Fi",
                  "Fantasy",
                  "Thriller",
                  "Romance",
                  "Horror",
                  "Mystery",
                  "Drama"
            ]
      },
      {
            "name": "themes",
            "label": "Themes/Topics",
            "type": "text",
            "placeholder": "e.g., AI, betrayal, redemption"
      },
      {
            "name": "format",
            "label": "Format",
            "type": "select",
            "options": [
                  "Short Story",
                  "Novel",
                  "Screenplay",
                  "Web Series"
            ]
      }
],
    promptTemplate: `Generate 5 unique story concepts in the {genre} genre for a {format}.

Themes to explore: {themes}

For each concept, provide:

**1. LOGLINE** (1-2 sentences)
- The entire story in a nutshell
- Include protagonist, conflict, and stakes

**2. PROTAGONIST**
- Name and brief description
- Fatal flaw or internal conflict
- What makes them unique

**3. CENTRAL CONFLICT**
- External: What they're fighting against
- Internal: What they're fighting within

**4. TWIST/HOOK**
- The unique angle that makes this story fresh
- What readers haven't seen before

**5. THEMATIC QUESTION**
- The deeper question the story explores

Make each concept distinct. Avoid clichés. Focus on character-driven narratives with high stakes.`
  },
  {
    id: 'product-description-ecommerce',
    category: 'writing',
    title: 'E-Commerce Product Description',
    icon: 'ShoppingCart',
    description: `Write persuasive product descriptions that convert browsers into buyers`,
    fields: [
      {
            "name": "product_name",
            "label": "Product Name",
            "type": "text"
      },
      {
            "name": "features",
            "label": "Key Features",
            "type": "textarea",
            "placeholder": "List main features"
      },
      {
            "name": "target_customer",
            "label": "Target Customer",
            "type": "text"
      },
      {
            "name": "price_point",
            "label": "Price Point",
            "type": "select",
            "options": [
                  "Budget",
                  "Mid-Range",
                  "Premium",
                  "Luxury"
            ]
      }
],
    promptTemplate: `Write a product description for {product_name} targeting {target_customer}.

Features: {features}
Price positioning: {price_point}

Structure:

**1. HEADLINE** (5-8 words)
- Lead with the main benefit, not the product name

**2. OPENING HOOK** (1-2 sentences)
- Describe the problem or desire
- Create emotional connection

**3. SENSORY DESCRIPTION** (2-3 sentences)
- How it looks, feels, sounds, smells
- Use vivid, specific adjectives
- Help them imagine owning it

**4. FEATURES → BENEFITS** (3-5 bullets)
- Don't just list features
- Translate each feature into "so you can..."
- Focus on outcomes

**5. SOCIAL PROOF**
- "Join [X] happy customers"
- Trust signals

**6. CTA**
- Action-oriented button text

Tone: Match {price_point} positioning (budget = practical, luxury = aspirational)
Length: 150-250 words
SEO: Naturally include product category keywords`
  },
  {
    id: 'blog-seo-article',
    category: 'writing',
    title: 'SEO Blog Article',
    icon: 'Article',
    description: `Write search-optimized blog posts that rank and convert`,
    fields: [
      {
            "name": "target_keyword",
            "label": "Target Keyword",
            "type": "text",
            "placeholder": "Primary keyword to rank for"
      },
      {
            "name": "search_intent",
            "label": "Search Intent",
            "type": "select",
            "options": [
                  "Informational",
                  "Commercial",
                  "Transactional",
                  "Navigational"
            ]
      },
      {
            "name": "word_count",
            "label": "Target Word Count",
            "type": "select",
            "options": [
                  "800-1200",
                  "1500-2000",
                  "2500+"
            ]
      },
      {
            "name": "audience_level",
            "label": "Audience Level",
            "type": "select",
            "options": [
                  "Beginner",
                  "Intermediate",
                  "Expert"
            ]
      }
],
    promptTemplate: `Write an SEO-optimized blog post targeting the keyword: "{target_keyword}"

Search intent: {search_intent}
Target length: {word_count} words
Audience: {audience_level}

**SEO REQUIREMENTS:**
- Include "{target_keyword}" in: title, first paragraph, one H2, meta description
- Use LSI keywords (related terms)
- Internal linking opportunities (suggest 3-5)
- External authority links (suggest 2-3)

**STRUCTURE:**

**Title (H1):** 
- Include "{target_keyword}"
- 50-60 characters
- Compelling + click-worthy

**Meta Description:**
- 150-160 characters
- Include keyword + CTA

**Introduction (100-150 words):**
- Hook with a question or stat
- Promise what they'll learn
- Include keyword naturally

**Body (H2 sections):**
- 3-5 main sections
- Use H3 subheadings
- Include:
  - Bullet points
  - Numbered lists
  - Bold key phrases
  - Short paragraphs (3-4 sentences max)

**Conclusion:**
- Summarize key points
- Clear CTA

**Tone:** {audience_level}-friendly, authoritative but accessible
**Formatting:** Scannable, visual hierarchy`
  },
  {
    id: 'twitter-thread-generator',
    category: 'writing',
    title: 'Viral Twitter/X Thread',
    icon: 'TwitterLogo',
    description: `Turn ideas into engaging Twitter threads that drive engagement`,
    fields: [
      {
            "name": "thread_topic",
            "label": "Thread Topic",
            "type": "text"
      },
      {
            "name": "key_points",
            "label": "Key Points",
            "type": "textarea",
            "placeholder": "Main ideas to cover"
      },
      {
            "name": "thread_goal",
            "label": "Thread Goal",
            "type": "select",
            "options": [
                  "Educate",
                  "Inspire",
                  "Entertain",
                  "Sell/Promote"
            ]
      }
],
    promptTemplate: `Create a Twitter/X thread about: {thread_topic}

Key points to cover: {key_points}
Goal: {thread_goal}

**THREAD STRUCTURE:**

**Tweet 1 (HOOK):**
- Controversial statement, surprising stat, or bold promise
- Make them NEED to click "Show this thread"
- End with "Here's what I learned:" or "A thread 🧵"

**Tweets 2-9 (BODY):**
- One idea per tweet
- Use:
  - Line breaks for readability
  - Bullet points (•)
  - Numbers (1/, 2/, 3/)
  - Emojis sparingly (max 1-2 per tweet)
- Keep each tweet 200-250 characters
- Each should work standalone

**Tweet 10 (CONCLUSION):**
- Summarize the key takeaway
- CTA: "Retweet if this helped" or "Follow me for more on [topic]"

**BONUS Tweet 11 (OPTIONAL):**
- Plug your product/newsletter/link
- "If you found this valuable, you'll love..."

**FORMATTING RULES:**
- No hashtags in thread (kills reach)
- Tag relevant accounts (max 1-2)
- First tweet should be quotable
- Use pattern interrupts (questions, stats, stories)

Generate 10-12 tweets total.`
  },
  {
    id: 'email-subject-lines',
    category: 'writing',
    title: 'Email Subject Line Generator',
    icon: 'At',
    description: `Create irresistible email subject lines that boost open rates`,
    fields: [
      {
            "name": "email_purpose",
            "label": "Email Purpose",
            "type": "text",
            "placeholder": "Product launch, newsletter, promotion, etc."
      },
      {
            "name": "audience",
            "label": "Audience",
            "type": "text"
      },
      {
            "name": "tone",
            "label": "Tone",
            "type": "select",
            "options": [
                  "Urgent",
                  "Curious",
                  "Friendly",
                  "Professional",
                  "Playful"
            ]
      }
],
    promptTemplate: `Generate 10 email subject lines for: {email_purpose}

Audience: {audience}
Tone: {tone}

Create 2 variations of each type:

**1. CURIOSITY GAP** (2 subject lines)
- Tease without revealing
- Example: "You're doing [X] wrong (here's why)"

**2. URGENCY/SCARCITY** (2 subject lines)
- Time-sensitive or limited
- Example: "Last chance: [Offer] ends tonight"

**3. PERSONALIZATION** (2 subject lines)
- Use "you" language
- Example: "{audience}, this is for you"

**4. BENEFIT-DRIVEN** (2 subject lines)
- Lead with the outcome
- Example: "Get [result] in [timeframe]"

**5. QUESTION** (2 subject lines)
- Make them think
- Example: "Are you making this [mistake]?"

**REQUIREMENTS:**
- 30-50 characters each
- No spam trigger words (FREE, !!!, ACT NOW)
- A/B test-ready (similar but distinct)
- Mobile-friendly (front-load key words)

Include predicted open rate for each (based on best practices).`
  },


// ========== CODING & DEVELOPMENT TEMPLATES ==========
  {
    id: 'refactor-code',
    category: 'code',
    title: 'Refactor Code',
    icon: 'Code',
    description: `Improve code quality, readability, and maintainability without changing functionality`,
    fields: [
      {
            "name": "code",
            "label": "Code to Refactor",
            "type": "textarea",
            "placeholder": "Paste your code here"
      },
      {
            "name": "language",
            "label": "Programming Language",
            "type": "text"
      },
      {
            "name": "focus",
            "label": "Refactoring Focus",
            "type": "select",
            "options": [
                  "Readability",
                  "Performance",
                  "SOLID Principles",
                  "DRY",
                  "All"
            ]
      }
],
    promptTemplate: `Refactor this {language} code with focus on: {focus}

Code:
```
{code}
```

Provide:
1. **Refactored Code**: Clean, improved version
2. **Changes Made**: Bullet list of specific improvements
3. **Why**: Explain the reasoning behind each change
4. **Before/After Metrics**: Complexity, lines of code, readability score

Follow best practices:
- Meaningful variable/function names
- Single Responsibility Principle
- Remove code duplication
- Add helpful comments
- Improve error handling`
  },
  {
    id: 'debug-fix-code',
    category: 'code',
    title: 'Debug & Fix Code',
    icon: 'Bug',
    description: `Identify and fix bugs with detailed explanations`,
    fields: [
      {
            "name": "code",
            "label": "Buggy Code",
            "type": "textarea"
      },
      {
            "name": "error_message",
            "label": "Error Message",
            "type": "textarea",
            "placeholder": "Paste error/stack trace"
      },
      {
            "name": "expected_behavior",
            "label": "Expected Behavior",
            "type": "text",
            "placeholder": "What should happen?"
      }
],
    promptTemplate: `Debug and fix this code.

Code:
```
{code}
```

Error message:
```
{error_message}
```

Expected behavior: {expected_behavior}

Provide:
1. **Root Cause**: What's causing the bug?
2. **Fixed Code**: Complete corrected version
3. **Explanation**: Line-by-line breakdown of the fix
4. **Prevention**: How to avoid this bug in the future
5. **Test Cases**: 3 test cases to verify the fix

Highlight the specific lines that were changed.`
  },
  {
    id: 'generate-function',
    category: 'code',
    title: 'Generate Function',
    icon: 'Function',
    description: `Create custom functions from natural language descriptions`,
    fields: [
      {
            "name": "description",
            "label": "Function Description",
            "type": "textarea",
            "placeholder": "Describe what the function should do"
      },
      {
            "name": "language",
            "label": "Language",
            "type": "select",
            "options": [
                  "Python",
                  "JavaScript",
                  "TypeScript",
                  "Java",
                  "C++",
                  "Go",
                  "Rust"
            ]
      },
      {
            "name": "inputs",
            "label": "Input Parameters",
            "type": "text",
            "placeholder": "e.g., array of numbers, string"
      },
      {
            "name": "output",
            "label": "Expected Output",
            "type": "text",
            "placeholder": "What should it return?"
      }
],
    promptTemplate: `Generate a {language} function that: {description}

Inputs: {inputs}
Output: {output}

Requirements:
1. **Function Signature**: Properly typed (if applicable)
2. **Implementation**: Clean, efficient code
3. **Error Handling**: Handle edge cases
4. **Documentation**: Docstring/JSDoc explaining parameters and return value
5. **Example Usage**: 2-3 examples showing how to call it
6. **Time/Space Complexity**: Big O notation

Follow {language} best practices and naming conventions.`
  },
  {
    id: 'code-review',
    category: 'code',
    title: 'Code Review',
    icon: 'MagnifyingGlass',
    description: `Get senior-level code review feedback on security, performance, and patterns`,
    fields: [
      {
            "name": "code",
            "label": "Code to Review",
            "type": "textarea"
      },
      {
            "name": "language",
            "label": "Language/Framework",
            "type": "text"
      },
      {
            "name": "review_focus",
            "label": "Review Focus",
            "type": "select",
            "options": [
                  "Security",
                  "Performance",
                  "Best Practices",
                  "All"
            ]
      }
],
    promptTemplate: `Perform a senior-level code review on this {language} code.

Focus: {review_focus}

Code:
```
{code}
```

Review checklist:
1. **Security Vulnerabilities**: SQL injection, XSS, authentication issues, etc.
2. **Performance Issues**: O(n²) operations, unnecessary loops, memory leaks
3. **Code Smells**: Long functions, god objects, tight coupling
4. **Best Practices**: SOLID principles, design patterns, naming conventions
5. **Edge Cases**: Null checks, boundary conditions, error handling

For each issue found:
- **Severity**: Critical/High/Medium/Low
- **Location**: Line number or function name
- **Problem**: What's wrong
- **Solution**: How to fix it
- **Example**: Show the corrected code

End with an overall score (1-10) and summary.`
  },
  {
    id: 'write-unit-tests',
    category: 'code',
    title: 'Write Unit Tests',
    icon: 'TestTube',
    description: `Generate comprehensive unit tests with edge cases`,
    fields: [
      {
            "name": "code",
            "label": "Code to Test",
            "type": "textarea"
      },
      {
            "name": "language",
            "label": "Language",
            "type": "text"
      },
      {
            "name": "framework",
            "label": "Testing Framework",
            "type": "select",
            "options": [
                  "Jest",
                  "Pytest",
                  "JUnit",
                  "Mocha",
                  "RSpec",
                  "Go Test"
            ]
      }
],
    promptTemplate: `Write comprehensive unit tests for this {language} code using {framework}.

Code to test:
```
{code}
```

Generate tests covering:
1. **Happy Path**: Normal, expected inputs
2. **Edge Cases**: Empty inputs, null, undefined, zero, negative numbers
3. **Boundary Conditions**: Min/max values, array limits
4. **Error Cases**: Invalid inputs, exceptions
5. **Integration**: How it works with dependencies (use mocks/stubs)

For each test:
- Descriptive test name
- Arrange-Act-Assert pattern
- Clear assertions
- Mock external dependencies

Include:
- Test setup/teardown if needed
- At least 8-10 test cases
- Code coverage estimate`
  },
  {
    id: 'api-design',
    category: 'code',
    title: 'API Design',
    icon: 'Globe',
    description: `Design RESTful or GraphQL APIs with best practices`,
    fields: [
      {
            "name": "resource",
            "label": "Resource/Entity",
            "type": "text",
            "placeholder": "e.g., User, Product, Order"
      },
      {
            "name": "api_type",
            "label": "API Type",
            "type": "select",
            "options": [
                  "REST",
                  "GraphQL",
                  "gRPC"
            ]
      },
      {
            "name": "operations",
            "label": "Required Operations",
            "type": "textarea",
            "placeholder": "List CRUD operations needed"
      }
],
    promptTemplate: `Design a {api_type} API for managing {resource}.

Required operations:
{operations}

Provide:

**1. ENDPOINTS** (for REST) or **SCHEMA** (for GraphQL):
- List all endpoints with HTTP methods
- URL structure following conventions
- Request/response examples

**2. DATA MODELS**:
- JSON schema for {resource}
- Field types and validations
- Relationships to other entities

**3. AUTHENTICATION**:
- Recommended auth method (JWT, OAuth, API keys)
- Protected vs public endpoints

**4. ERROR HANDLING**:
- Standard error response format
- HTTP status codes
- Error messages

**5. BEST PRACTICES**:
- Versioning strategy
- Pagination for lists
- Rate limiting
- HATEOAS links (if REST)

**6. EXAMPLE REQUESTS**:
- cURL examples for each endpoint
- Expected responses

Follow {api_type} conventions and industry standards.`
  },
  {
    id: 'sql-query-builder',
    category: 'code',
    title: 'SQL Query Builder',
    icon: 'Database',
    description: `Generate optimized SQL queries from natural language`,
    fields: [
      {
            "name": "description",
            "label": "Query Description",
            "type": "textarea",
            "placeholder": "Describe what data you need"
      },
      {
            "name": "database",
            "label": "Database Type",
            "type": "select",
            "options": [
                  "PostgreSQL",
                  "MySQL",
                  "SQL Server",
                  "SQLite",
                  "Oracle"
            ]
      },
      {
            "name": "tables",
            "label": "Table Names",
            "type": "text",
            "placeholder": "Comma-separated table names"
      }
],
    promptTemplate: `Generate a {database} SQL query for: {description}

Tables involved: {tables}

Provide:
1. **The Query**: Formatted, readable SQL
2. **Explanation**: What each part does
3. **Indexes Needed**: Suggest indexes for performance
4. **Execution Plan**: Expected query performance
5. **Alternative Approaches**: If there's a better way

Optimize for:
- Performance (avoid N+1, use JOINs wisely)
- Readability (proper formatting, aliases)
- Security (parameterized, no SQL injection risk)

Include:
- Proper JOINs (INNER, LEFT, etc.)
- WHERE clauses with correct logic
- GROUP BY and HAVING if needed
- ORDER BY and LIMIT
- Comments explaining complex parts`
  },
  {
    id: 'regex-pattern-generator',
    category: 'code',
    title: 'Regex Pattern Generator',
    icon: 'Asterisk',
    description: `Create and explain complex regular expressions`,
    fields: [
      {
            "name": "pattern_description",
            "label": "What to Match",
            "type": "textarea",
            "placeholder": "e.g., Email addresses, phone numbers, URLs"
      },
      {
            "name": "language",
            "label": "Language/Flavor",
            "type": "select",
            "options": [
                  "JavaScript",
                  "Python",
                  "Java",
                  "PCRE",
                  "Golang"
            ]
      },
      {
            "name": "examples",
            "label": "Example Matches",
            "type": "textarea",
            "placeholder": "Provide 2-3 examples that should match"
      }
],
    promptTemplate: `Create a regular expression to match: {pattern_description}

Language/Flavor: {language}
Should match these examples:
{examples}

Provide:
1. **The Regex Pattern**: Complete expression
2. **Breakdown**: Explain each part:
   - `^` and `$` (anchors)
   - `[]` (character classes)
   - `()` (capture groups)
   - `*`, `+`, `?` (quantifiers)
   - `\d`, `\w`, `\s` (shortcuts)
3. **Test Cases**:
   - 5 strings that SHOULD match
   - 5 strings that should NOT match
4. **Code Example**: How to use it in {language}
5. **Performance Notes**: Any optimization tips

Make it readable with comments (using `(?# comment)` if supported).`
  },
  {
    id: 'code-documentation',
    category: 'code',
    title: 'Code Documentation',
    icon: 'FileDoc',
    description: `Generate comprehensive documentation for code`,
    fields: [
      {
            "name": "code",
            "label": "Code to Document",
            "type": "textarea"
      },
      {
            "name": "language",
            "label": "Language",
            "type": "text"
      },
      {
            "name": "doc_style",
            "label": "Documentation Style",
            "type": "select",
            "options": [
                  "JSDoc",
                  "Docstring (Python)",
                  "Javadoc",
                  "GoDoc",
                  "RDoc"
            ]
      }
],
    promptTemplate: `Generate {doc_style} documentation for this {language} code:

```
{code}
```

Include:
1. **Function/Class Description**: What it does, why it exists
2. **Parameters**: Each parameter with:
   - Type
   - Description
   - Default value (if any)
   - Constraints/validation
3. **Return Value**: Type and description
4. **Exceptions/Errors**: What can go wrong
5. **Examples**: 2-3 usage examples
6. **Notes**: Performance considerations, gotchas
7. **See Also**: Related functions/classes

Follow {doc_style} format exactly.
Make it beginner-friendly but technically accurate.`
  },
  {
    id: 'cli-tool-script',
    category: 'code',
    title: 'CLI Tool Script',
    icon: 'Terminal',
    description: `Create command-line tools and scripts`,
    fields: [
      {
            "name": "tool_purpose",
            "label": "Tool Purpose",
            "type": "textarea",
            "placeholder": "What should this CLI tool do?"
      },
      {
            "name": "language",
            "label": "Language",
            "type": "select",
            "options": [
                  "Python",
                  "Bash",
                  "Node.js",
                  "Go"
            ]
      },
      {
            "name": "arguments",
            "label": "Command Arguments",
            "type": "textarea",
            "placeholder": "List required and optional arguments"
      }
],
    promptTemplate: `Create a {language} CLI tool that: {tool_purpose}

Arguments:
{arguments}

Generate:
1. **Complete Script**: Production-ready code
2. **Argument Parsing**: Handle flags and options properly
3. **Help Text**: `--help` output
4. **Error Handling**: Validate inputs, show helpful errors
5. **Usage Examples**: How to run it
6. **Installation**: How to make it executable

Include:
- Shebang line (if applicable)
- Proper exit codes (0 for success, 1+ for errors)
- Colored output (optional)
- Progress indicators for long operations
- Configuration file support (if complex)

Make it user-friendly with clear error messages.`
  },
  {
    id: 'docker-configuration',
    category: 'code',
    title: 'Docker Configuration',
    icon: 'Package',
    description: `Generate Dockerfiles and docker-compose files`,
    fields: [
      {
            "name": "app_type",
            "label": "Application Type",
            "type": "text",
            "placeholder": "e.g., Node.js API, Python Flask, React app"
      },
      {
            "name": "dependencies",
            "label": "Dependencies",
            "type": "textarea",
            "placeholder": "List required services (DB, Redis, etc.)"
      },
      {
            "name": "environment",
            "label": "Environment",
            "type": "select",
            "options": [
                  "Development",
                  "Production",
                  "Both"
            ]
      }
],
    promptTemplate: `Create Docker configuration for a {app_type} application.

Dependencies: {dependencies}
Environment: {environment}

Generate:

**1. Dockerfile**:
- Appropriate base image
- Multi-stage build (for production)
- Layer optimization
- Security best practices (non-root user)
- Health check

**2. docker-compose.yml**:
- Main application service
- All dependencies from {dependencies}
- Volume mounts
- Environment variables
- Network configuration
- Port mappings

**3. .dockerignore**:
- Files to exclude

**4. README section**:
- How to build: `docker build`
- How to run: `docker-compose up`
- Environment variables needed

**5. Best Practices Applied**:
- Minimal image size
- Build caching
- Security scanning

Include comments explaining each section.`
  },
  {
    id: 'cicd-pipeline',
    category: 'code',
    title: 'CI/CD Pipeline',
    icon: 'GitBranch',
    description: `Create GitHub Actions, GitLab CI, or Jenkins pipelines`,
    fields: [
      {
            "name": "platform",
            "label": "CI/CD Platform",
            "type": "select",
            "options": [
                  "GitHub Actions",
                  "GitLab CI",
                  "Jenkins",
                  "CircleCI"
            ]
      },
      {
            "name": "project_type",
            "label": "Project Type",
            "type": "text",
            "placeholder": "e.g., Node.js, Python, Java"
      },
      {
            "name": "deployment_target",
            "label": "Deployment Target",
            "type": "select",
            "options": [
                  "AWS",
                  "Google Cloud",
                  "Azure",
                  "Heroku",
                  "Vercel",
                  "Self-hosted"
            ]
      }
],
    promptTemplate: `Create a {platform} pipeline for a {project_type} project deploying to {deployment_target}.

Pipeline stages:
1. **Build**
2. **Test**
3. **Security Scan**
4. **Deploy**

Generate:

**1. Pipeline Configuration File**:
- Proper YAML/Groovy syntax for {platform}
- Trigger conditions (push, PR, tags)
- Environment variables
- Secrets management

**2. Build Stage**:
- Install dependencies
- Compile/bundle
- Cache dependencies

**3. Test Stage**:
- Unit tests
- Integration tests
- Code coverage
- Linting

**4. Security Stage**:
- Dependency vulnerability scan
- SAST (static analysis)
- Container scanning (if applicable)

**5. Deploy Stage**:
- Deploy to {deployment_target}
- Environment-specific configs (staging, production)
- Rollback strategy

**6. Notifications**:
- Slack/email on failure

Include comments and best practices for {platform}.`
  },
  {
    id: 'security-audit',
    category: 'code',
    title: 'Security Audit',
    icon: 'Shield',
    description: `Identify security vulnerabilities in code`,
    fields: [
      {
            "name": "code",
            "label": "Code to Audit",
            "type": "textarea"
      },
      {
            "name": "language",
            "label": "Language/Framework",
            "type": "text"
      },
      {
            "name": "app_type",
            "label": "Application Type",
            "type": "select",
            "options": [
                  "Web App",
                  "API",
                  "Mobile App",
                  "CLI Tool",
                  "Library"
            ]
      }
],
    promptTemplate: `Perform a security audit on this {language} {app_type} code.

Code:
```
{code}
```

Check for:

**1. INJECTION ATTACKS**:
- SQL Injection
- NoSQL Injection
- Command Injection
- XSS (Cross-Site Scripting)
- LDAP Injection

**2. AUTHENTICATION & AUTHORIZATION**:
- Weak password policies
- Missing authentication
- Broken access control
- Session management issues

**3. DATA EXPOSURE**:
- Sensitive data in logs
- Unencrypted data transmission
- Exposed API keys/secrets
- Information disclosure

**4. CRYPTOGRAPHY**:
- Weak hashing algorithms
- Hardcoded secrets
- Insecure random number generation

**5. CONFIGURATION**:
- Debug mode in production
- Default credentials
- Unnecessary services enabled

For each vulnerability:
- **OWASP Category**: (if applicable)
- **Severity**: Critical/High/Medium/Low
- **Exploit Scenario**: How an attacker could use it
- **Fix**: Secure code example
- **Prevention**: Best practices

Provide a security score (0-100) and prioritized fix list.`
  },
  {
    id: 'algorithm-design',
    category: 'code',
    title: 'Algorithm Design',
    icon: 'FlowArrow',
    description: `Design efficient algorithms for complex problems`,
    fields: [
      {
            "name": "problem",
            "label": "Problem Description",
            "type": "textarea",
            "placeholder": "Describe the problem to solve"
      },
      {
            "name": "constraints",
            "label": "Constraints",
            "type": "textarea",
            "placeholder": "Input size, time limits, etc."
      },
      {
            "name": "language",
            "label": "Implementation Language",
            "type": "select",
            "options": [
                  "Python",
                  "JavaScript",
                  "C++",
                  "Java",
                  "Go",
                  "Pseudocode"
            ]
      }
],
    promptTemplate: `Design an efficient algorithm to solve: {problem}

Constraints: {constraints}

Provide:

**1. APPROACH**:
- High-level strategy
- Why this approach is optimal
- Alternative approaches considered

**2. ALGORITHM**:
- Step-by-step pseudocode
- Key data structures used

**3. IMPLEMENTATION** (in {language}):
- Clean, commented code
- Helper functions if needed

**4. COMPLEXITY ANALYSIS**:
- Time Complexity: O(?)
- Space Complexity: O(?)
- Proof/explanation of complexity

**5. EXAMPLES**:
- Input → Output walkthrough
- Edge cases handled

**6. OPTIMIZATIONS**:
- How to improve further
- Trade-offs made

**7. TEST CASES**:
- Normal cases
- Edge cases
- Large inputs

Make it interview-ready with clear explanations.`
  },
  {
    id: 'database-migration',
    category: 'code',
    title: 'Database Migration',
    icon: 'Database',
    description: `Create database migration scripts with rollback support`,
    fields: [
      {
            "name": "migration_description",
            "label": "Migration Description",
            "type": "textarea",
            "placeholder": "What changes are you making?"
      },
      {
            "name": "database",
            "label": "Database",
            "type": "select",
            "options": [
                  "PostgreSQL",
                  "MySQL",
                  "MongoDB",
                  "SQL Server"
            ]
      },
      {
            "name": "orm",
            "label": "ORM/Tool",
            "type": "select",
            "options": [
                  "Raw SQL",
                  "Prisma",
                  "TypeORM",
                  "Sequelize",
                  "Alembic",
                  "Flyway"
            ]
      }
],
    promptTemplate: `Create a database migration for: {migration_description}

Database: {database}
Tool: {orm}

Generate:

**1. UP MIGRATION** (apply changes):
- CREATE TABLE / ALTER TABLE statements
- Add indexes
- Add constraints
- Data transformations (if needed)

**2. DOWN MIGRATION** (rollback):
- Reverse all changes
- Restore previous state

**3. SAFETY CHECKS**:
- Check if table/column exists before creating
- Handle existing data
- Prevent data loss

**4. PERFORMANCE CONSIDERATIONS**:
- Index creation strategy (CONCURRENTLY if supported)
- Batch data updates
- Lock minimization

**5. TESTING PLAN**:
- How to test the migration
- Rollback testing
- Data validation queries

**6. DEPLOYMENT NOTES**:
- Downtime required? (yes/no)
- Order of operations
- Backup recommendation

Follow {orm} syntax and {database} best practices.
Include comments explaining each step.`
  },


// ========== PRODUCTIVITY & PLANNING TEMPLATES ==========
  {
    id: 'project-plan-generator',
    category: 'productivity',
    title: 'Project Plan Generator',
    icon: 'Kanban',
    description: `Create comprehensive project plans with milestones, tasks, and timelines`,
    fields: [
      {
            "name": "project_name",
            "label": "Project Name",
            "type": "text"
      },
      {
            "name": "project_goal",
            "label": "Project Goal",
            "type": "textarea",
            "placeholder": "What are you trying to achieve?"
      },
      {
            "name": "deadline",
            "label": "Deadline",
            "type": "text",
            "placeholder": "e.g., 3 months, Q2 2024"
      },
      {
            "name": "team_size",
            "label": "Team Size",
            "type": "select",
            "options": [
                  "Solo",
                  "2-5 people",
                  "6-10 people",
                  "10+ people"
            ]
      }
],
    promptTemplate: `Create a comprehensive project plan for: {project_name}

Goal: {project_goal}
Deadline: {deadline}
Team: {team_size}

Generate:

**1. PROJECT OVERVIEW**
- Objective (SMART goal)
- Success criteria
- Key stakeholders

**2. PHASES & MILESTONES**
Break into 4-6 phases:
- Phase name
- Duration
- Key deliverables
- Milestone criteria

**3. TASK BREAKDOWN** (for each phase)
- Task name
- Owner (role)
- Estimated hours
- Dependencies
- Priority (High/Medium/Low)

**4. TIMELINE**
- Gantt chart structure (text-based)
- Critical path
- Buffer time

**5. RESOURCES NEEDED**
- Team roles
- Tools/software
- Budget estimate

**6. RISK MANAGEMENT**
- Top 3 risks
- Mitigation strategies

**7. COMMUNICATION PLAN**
- Meeting cadence
- Status update frequency
- Reporting structure

Format as a structured document ready to share with the team.`
  },
  {
    id: 'daily-schedule-optimizer',
    category: 'productivity',
    title: 'Daily Schedule Optimizer',
    icon: 'Clock',
    description: `Optimize your daily schedule based on energy levels and priorities`,
    fields: [
      {
            "name": "work_hours",
            "label": "Available Work Hours",
            "type": "text",
            "placeholder": "e.g., 9am-6pm"
      },
      {
            "name": "tasks",
            "label": "Tasks to Schedule",
            "type": "textarea",
            "placeholder": "List your tasks for the day"
      },
      {
            "name": "energy_pattern",
            "label": "Energy Pattern",
            "type": "select",
            "options": [
                  "Morning person",
                  "Night owl",
                  "Consistent energy",
                  "Afternoon peak"
            ]
      },
      {
            "name": "meeting_blocks",
            "label": "Fixed Meetings",
            "type": "textarea",
            "placeholder": "List any scheduled meetings"
      }
],
    promptTemplate: `Optimize my daily schedule for maximum productivity.

Available hours: {work_hours}
Tasks: {tasks}
Energy pattern: {energy_pattern}
Fixed meetings: {meeting_blocks}

Create an optimized schedule using:

**1. TIME BLOCKING**
- Deep work blocks (90-120 min)
- Shallow work blocks (30-60 min)
- Break times (Pomodoro technique)

**2. ENERGY ALIGNMENT**
Based on {energy_pattern}:
- Schedule high-cognitive tasks during peak energy
- Admin/email during low energy
- Creative work when fresh

**3. TASK PRIORITIZATION**
Use Eisenhower Matrix:
- Urgent & Important (do first)
- Important, not urgent (schedule)
- Urgent, not important (delegate/batch)
- Neither (eliminate)

**4. BUFFER TIME**
- 10-15 min between tasks
- Unexpected interruptions
- Transition time

**5. DAILY STRUCTURE**
Format:
```
9:00-9:30   Morning routine + planning
9:30-11:00  [DEEP WORK] Task X
11:00-11:15 Break
...
```

Include:
- Task batching opportunities
- Email/Slack check times (2-3x max)
- Lunch break
- End-of-day review (15 min)`
  },
  {
    id: 'habit-building-plan',
    category: 'productivity',
    title: 'Habit Building Plan',
    icon: 'Target',
    description: `Design a science-backed plan to build lasting habits`,
    fields: [
      {
            "name": "habit_goal",
            "label": "Habit to Build",
            "type": "text",
            "placeholder": "e.g., Exercise daily, read 30 min, meditate"
      },
      {
            "name": "current_frequency",
            "label": "Current Frequency",
            "type": "select",
            "options": [
                  "Never",
                  "Rarely",
                  "Sometimes",
                  "Often"
            ]
      },
      {
            "name": "obstacles",
            "label": "Main Obstacles",
            "type": "textarea",
            "placeholder": "What stops you?"
      },
      {
            "name": "timeframe",
            "label": "Timeframe",
            "type": "select",
            "options": [
                  "21 days",
                  "30 days",
                  "66 days",
                  "90 days"
            ]
      }
],
    promptTemplate: `Create a habit-building plan to: {habit_goal}

Current state: {current_frequency}
Obstacles: {obstacles}
Timeframe: {timeframe}

Use James Clear's Atomic Habits framework:

**1. MAKE IT OBVIOUS**
- Implementation intention: "I will [BEHAVIOR] at [TIME] in [LOCATION]"
- Habit stacking: "After [CURRENT HABIT], I will [NEW HABIT]"
- Environment design: Visual cues to trigger the habit

**2. MAKE IT ATTRACTIVE**
- Temptation bundling: Pair with something you enjoy
- Join a culture where {habit_goal} is normal
- Reframe mindset: "I GET to" not "I HAVE to"

**3. MAKE IT EASY**
- 2-minute rule: Start with tiny version
- Reduce friction: Prepare environment night before
- Prime the environment: Lay out workout clothes, etc.

**4. MAKE IT SATISFYING**
- Immediate reward after completion
- Habit tracker (visual progress)
- Never miss twice rule

**WEEKLY PLAN** ({timeframe}):
Week 1: [Tiny habit version]
Week 2: [Slightly increased]
Week 3-4: [Full habit]
...

**OBSTACLE MITIGATION**:
For each obstacle in {obstacles}:
- If-then plan: "If [OBSTACLE], then I will [RESPONSE]"

**TRACKING METHOD**:
- Daily checkbox
- Streak counter
- Accountability partner

**IDENTITY SHIFT**:
- "I am someone who [habit_goal]"
- Evidence collection`
  },
  {
    id: 'decision-matrix',
    category: 'productivity',
    title: 'Decision Matrix',
    icon: 'ChartBar',
    description: `Make better decisions using weighted criteria analysis`,
    fields: [
      {
            "name": "decision",
            "label": "Decision to Make",
            "type": "text",
            "placeholder": "e.g., Choose between job offers, pick a vendor"
      },
      {
            "name": "options",
            "label": "Options",
            "type": "textarea",
            "placeholder": "List 2-5 options (one per line)"
      },
      {
            "name": "criteria",
            "label": "Decision Criteria",
            "type": "textarea",
            "placeholder": "What factors matter? (e.g., cost, time, quality)"
      },
      {
            "name": "decision_type",
            "label": "Decision Type",
            "type": "select",
            "options": [
                  "Career",
                  "Business",
                  "Personal",
                  "Purchase"
            ]
      }
],
    promptTemplate: `Help me decide: {decision}

Options:
{options}

Criteria to consider:
{criteria}

Create a decision matrix:

**1. WEIGHTED CRITERIA**
For each criterion in {criteria}:
- Importance weight (1-10)
- Why it matters for {decision_type} decisions

**2. SCORING MATRIX**
Table format:
| Criteria (Weight) | Option 1 | Option 2 | Option 3 |
|-------------------|----------|----------|----------|
| [Criterion] (8)   | 7/10     | 9/10     | 6/10     |
| [Criterion] (5)   | 8/10     | 6/10     | 9/10     |

**3. WEIGHTED SCORES**
Calculate: (Score × Weight) for each cell
Total for each option

**4. QUALITATIVE ANALYSIS**
Beyond numbers:
- Gut feeling check
- Reversibility (can you undo this?)
- Regret minimization: "Will I regret NOT choosing X?"

**5. SECOND-ORDER CONSEQUENCES**
- What happens after the decision?
- Opportunity cost
- Long-term vs short-term trade-offs

**6. RECOMMENDATION**
- Top choice with reasoning
- Runner-up
- Deal-breakers to watch for

**7. PRE-MORTEM**
"It's 6 months later and this decision failed. Why?"
- Identify risks for top choice`
  },
  {
    id: 'weekly-review-template',
    category: 'productivity',
    title: 'Weekly Review Template',
    icon: 'CalendarCheck',
    description: `Conduct effective weekly reviews to stay on track with goals`,
    fields: [
      {
            "name": "week_ending",
            "label": "Week Ending",
            "type": "text",
            "placeholder": "Date"
      },
      {
            "name": "goals",
            "label": "This Week's Goals",
            "type": "textarea",
            "placeholder": "What did you plan to accomplish?"
      },
      {
            "name": "focus_area",
            "label": "Focus Area",
            "type": "select",
            "options": [
                  "Work",
                  "Personal",
                  "Health",
                  "Learning",
                  "All"
            ]
      }
],
    promptTemplate: `Create a weekly review template for the week ending: {week_ending}

Planned goals: {goals}
Focus: {focus_area}

**PART 1: LOOK BACK**

**1. Wins & Accomplishments**
- What went well?
- What am I proud of?
- Unexpected victories?

**2. Challenges & Obstacles**
- What didn't go as planned?
- Why? (root cause)
- What did I learn?

**3. Goal Progress**
For each goal in {goals}:
- ✅ Completed / ⏳ In Progress / ❌ Not Started
- % complete
- Blockers

**4. Time Audit**
- Where did time actually go?
- Time wasters identified
- Best use of time this week

**5. Energy Audit**
- What energized me?
- What drained me?
- Adjustments needed

**PART 2: LOOK AHEAD**

**6. Next Week's Priorities**
Using MITs (Most Important Tasks):
- MIT 1: [Must complete]
- MIT 2: [Must complete]
- MIT 3: [Must complete]
- Secondary tasks: [Nice to have]

**7. Calendar Review**
- Upcoming meetings/deadlines
- Time blocks needed
- Conflicts to resolve

**8. Habit Check**
- Habits maintained
- Habits to start/stop
- Streak status

**9. One Thing to Improve**
- Single focus for next week
- Specific action plan

**10. Gratitude & Mindset**
- 3 things I'm grateful for
- Affirmation for next week

**METRICS** (if applicable):
- Key numbers tracked
- Progress toward quarterly goals
- Health/fitness stats`
  },
  {
    id: 'goal-breakdown',
    category: 'productivity',
    title: 'Goal Breakdown & Action Plan',
    icon: 'Crosshair',
    description: `Break down big goals into actionable steps using SMART framework`,
    fields: [
      {
            "name": "big_goal",
            "label": "Big Goal",
            "type": "text",
            "placeholder": "Your ambitious goal"
      },
      {
            "name": "timeline",
            "label": "Timeline",
            "type": "select",
            "options": [
                  "1 month",
                  "3 months",
                  "6 months",
                  "1 year"
            ]
      },
      {
            "name": "current_state",
            "label": "Current State",
            "type": "textarea",
            "placeholder": "Where are you now?"
      },
      {
            "name": "resources",
            "label": "Available Resources",
            "type": "textarea",
            "placeholder": "Time, money, skills, network"
      }
],
    promptTemplate: `Break down this goal into an actionable plan: {big_goal}

Timeline: {timeline}
Current state: {current_state}
Resources: {resources}

**1. SMART GOAL REFINEMENT**
Make {big_goal} SMART:
- **S**pecific: Exactly what will be achieved?
- **M**easurable: How will you track progress?
- **A**chievable: Is it realistic given {resources}?
- **R**elevant: Why does this matter?
- **T**ime-bound: Deadline within {timeline}

**2. REVERSE ENGINEERING**
Work backwards from {big_goal}:
- End state (100%)
- 75% milestone
- 50% milestone
- 25% milestone
- Starting point (current state)

**3. QUARTERLY BREAKDOWN** (if timeline > 3 months)
Q1: [Focus & deliverables]
Q2: [Focus & deliverables]
...

**4. MONTHLY MILESTONES**
For each month in {timeline}:
- Month X objective
- Success criteria
- Key activities

**5. WEEKLY ACTIONS** (First 4 weeks)
Week 1:
- [ ] Action 1
- [ ] Action 2
- [ ] Action 3

**6. FIRST STEP** (Do this today)
- Specific action
- Takes < 30 minutes
- Builds momentum

**7. OBSTACLES & SOLUTIONS**
Likely obstacles:
- Obstacle 1 → Solution
- Obstacle 2 → Solution

**8. ACCOUNTABILITY**
- How will you track?
- Who will you report to?
- Review frequency

**9. RESOURCES NEEDED**
- Skills to learn
- Tools to acquire
- People to connect with
- Money to invest

**10. SUCCESS METRICS**
- Leading indicators (activity)
- Lagging indicators (results)
- Check-in schedule`
  },
  {
    id: 'meeting-notes-template',
    category: 'productivity',
    title: 'Meeting Notes Template',
    icon: 'Note',
    description: `Capture actionable meeting notes with clear next steps`,
    fields: [
      {
            "name": "meeting_title",
            "label": "Meeting Title",
            "type": "text"
      },
      {
            "name": "meeting_type",
            "label": "Meeting Type",
            "type": "select",
            "options": [
                  "Standup",
                  "Planning",
                  "Retrospective",
                  "1-on-1",
                  "Client Call",
                  "Brainstorm"
            ]
      },
      {
            "name": "attendees",
            "label": "Attendees",
            "type": "text",
            "placeholder": "Names or roles"
      },
      {
            "name": "duration",
            "label": "Duration",
            "type": "select",
            "options": [
                  "15 min",
                  "30 min",
                  "1 hour",
                  "2+ hours"
            ]
      }
],
    promptTemplate: `Create a meeting notes template for: {meeting_title}

Type: {meeting_type}
Attendees: {attendees}
Duration: {duration}

**MEETING HEADER**
- Date: [Auto-fill]
- Time: [Auto-fill]
- Location/Link: [Fill in]
- Notetaker: [Fill in]

**AGENDA**
1. [Topic 1] - X min
2. [Topic 2] - X min
3. [Topic 3] - X min

**MEETING OBJECTIVE**
What we need to accomplish: [Fill in]

**DISCUSSION NOTES**

For each agenda item:

**[Topic Name]**
- Key points discussed:
  - Point 1
  - Point 2
- Decisions made:
  - ✅ Decision 1
  - ✅ Decision 2
- Questions raised:
  - ❓ Question 1
  - ❓ Question 2

**ACTION ITEMS** ⚡
Critical section - be specific!

| Action | Owner | Deadline | Priority |
|--------|-------|----------|----------|
| [Task] | @Name | MM/DD    | High     |
| [Task] | @Name | MM/DD    | Medium   |

**DECISIONS LOG** 📋
- Decision 1: [What was decided and why]
- Decision 2: [What was decided and why]

**PARKING LOT** 🅿️
Items to discuss later:
- Item 1
- Item 2

**NEXT STEPS**
- Next meeting: [Date/Time]
- Pre-work needed: [What to prepare]
- Follow-up: [Who sends what to whom]

**MEETING METRICS** (optional)
- Started on time: Y/N
- Ended on time: Y/N
- Agenda followed: Y/N
- Action items clear: Y/N

**NOTES FOR {meeting_type} MEETINGS:**
{meeting_type === 'Standup' ? '- Yesterday, Today, Blockers format' : ''}
{meeting_type === 'Retrospective' ? '- Start, Stop, Continue framework' : ''}
{meeting_type === '1-on-1' ? '- Career development, feedback, concerns' : ''}`
  },
  {
    id: 'email-templates-library',
    category: 'productivity',
    title: 'Reusable Email Templates',
    icon: 'EnvelopeSimple',
    description: `Create a library of email templates for common scenarios`,
    fields: [
      {
            "name": "scenario",
            "label": "Email Scenario",
            "type": "select",
            "options": [
                  "Follow-up",
                  "Introduction",
                  "Request",
                  "Decline",
                  "Thank You",
                  "Update",
                  "Apology"
            ]
      },
      {
            "name": "context",
            "label": "Context",
            "type": "textarea",
            "placeholder": "Provide context for the email"
      },
      {
            "name": "tone",
            "label": "Tone",
            "type": "select",
            "options": [
                  "Formal",
                  "Professional",
                  "Friendly",
                  "Casual"
            ]
      }
],
    promptTemplate: `Create reusable email templates for: {scenario}

Context: {context}
Tone: {tone}

Generate 3 variations for different situations:

**TEMPLATE 1: SHORT VERSION** (< 100 words)
Subject: [Template subject line]

Hi [Name],

[2-3 sentence body]

[CTA]

Best,
[Your name]

**When to use:** Quick touchpoints, busy recipients

---

**TEMPLATE 2: STANDARD VERSION** (100-200 words)
Subject: [Template subject line]

Hi [Name],

[Opening line - context/reference]

[2-3 paragraphs with details]

[Clear ask or next step]

[Closing]

Best regards,
[Your name]

**When to use:** Most common situations

---

**TEMPLATE 3: DETAILED VERSION** (200+ words)
Subject: [Template subject line]

Dear [Name],

[Formal opening]

[Background context]

[Main content - 3-4 paragraphs]

[Specific request with details]

[Timeline and expectations]

[Closing with appreciation]

Sincerely,
[Your name]

**When to use:** Important stakeholders, formal requests

---

**CUSTOMIZATION TIPS:**
- Placeholders to fill: [List them]
- Tone adjustments for different audiences
- Common mistakes to avoid

**FOLLOW-UP STRATEGY:**
- When to send: [Timing]
- If no response: [Next steps]
- Escalation path: [If needed]`
  },
  {
    id: 'travel-itinerary',
    category: 'productivity',
    title: 'Travel Itinerary Planner',
    icon: 'Airplane',
    description: `Plan detailed travel itineraries with logistics and backup plans`,
    fields: [
      {
            "name": "destination",
            "label": "Destination",
            "type": "text"
      },
      {
            "name": "duration",
            "label": "Trip Duration",
            "type": "text",
            "placeholder": "e.g., 5 days"
      },
      {
            "name": "trip_type",
            "label": "Trip Type",
            "type": "select",
            "options": [
                  "Business",
                  "Leisure",
                  "Mixed",
                  "Adventure"
            ]
      },
      {
            "name": "priorities",
            "label": "Priorities",
            "type": "textarea",
            "placeholder": "What do you want to do/see?"
      }
],
    promptTemplate: `Create a detailed travel itinerary for: {destination}

Duration: {duration}
Type: {trip_type}
Priorities: {priorities}

**TRIP OVERVIEW**
- Dates: [Fill in]
- Travelers: [Fill in]
- Budget: [Fill in]

**PRE-TRIP CHECKLIST** ✈️
- [ ] Flights booked
- [ ] Accommodation confirmed
- [ ] Travel insurance
- [ ] Visa/passport check
- [ ] Vaccinations (if needed)
- [ ] Currency exchange
- [ ] Phone/data plan
- [ ] Copies of documents

**DAY-BY-DAY ITINERARY**

For each day of {duration}:

**Day X - [Theme/Focus]**

*Morning (8am-12pm)*
- 8:00am: [Activity]
  - Location: [Address]
  - Cost: $X
  - Booking: [Link/confirmation]
  - Travel time: X min
  - Notes: [Tips]

*Afternoon (12pm-6pm)*
- 12:00pm: Lunch at [Restaurant]
- 2:00pm: [Activity]

*Evening (6pm-10pm)*
- 6:00pm: [Activity]
- 8:00pm: Dinner

*Backup Plan*: If weather is bad / attraction closed

**LOGISTICS**

**Transportation**
- Airport → Hotel: [Method, cost, time]
- Getting around: [Public transit, rental car, etc.]
- Key routes/apps

**Accommodation**
- Hotel: [Name, address, confirmation #]
- Check-in: [Time]
- Check-out: [Time]
- Amenities: [WiFi, breakfast, etc.]

**Dining Reservations**
| Restaurant | Date | Time | Confirmation |
|------------|------|------|--------------|
| [Name]     | Day 2| 7pm  | #12345       |

**BUDGET BREAKDOWN**
- Flights: $X
- Accommodation: $X
- Food: $X/day
- Activities: $X
- Transportation: $X
- Misc: $X
- **Total**: $X

**PACKING LIST** 🎒
*Essentials*
- [ ] Passport/ID
- [ ] Tickets/confirmations
- [ ] Chargers
- [ ] Medications

*Clothing* (based on weather)
- [ ] [Items]

*Tech*
- [ ] Phone + charger
- [ ] Camera
- [ ] Power adapter

**IMPORTANT CONTACTS**
- Embassy: [Phone]
- Hotel: [Phone]
- Emergency: [Local 911 equivalent]
- Travel insurance: [Phone, policy #]

**LOCAL INFO**
- Language: [Key phrases]
- Currency: [Exchange rate]
- Tipping: [Customs]
- Emergency numbers: [List]
- WiFi: [Where to find]

**BACKUP PLANS**
- Bad weather alternatives
- Closed attraction backups
- Restaurant alternatives`
  },
  {
    id: 'event-planning-checklist',
    category: 'productivity',
    title: 'Event Planning Checklist',
    icon: 'Confetti',
    description: `Plan and execute successful events with comprehensive checklists`,
    fields: [
      {
            "name": "event_name",
            "label": "Event Name",
            "type": "text"
      },
      {
            "name": "event_type",
            "label": "Event Type",
            "type": "select",
            "options": [
                  "Conference",
                  "Workshop",
                  "Party",
                  "Wedding",
                  "Webinar",
                  "Meetup"
            ]
      },
      {
            "name": "attendee_count",
            "label": "Expected Attendees",
            "type": "select",
            "options": [
                  "< 25",
                  "25-50",
                  "50-100",
                  "100-500",
                  "500+"
            ]
      },
      {
            "name": "event_date",
            "label": "Event Date",
            "type": "text",
            "placeholder": "Target date"
      }
],
    promptTemplate: `Create an event planning checklist for: {event_name}

Type: {event_type}
Attendees: {attendee_count}
Date: {event_date}

**EVENT OVERVIEW**
- Objective: [What's the goal?]
- Target audience: [Who's attending?]
- Budget: $[Amount]
- Theme/Vibe: [Description]

**TIMELINE CHECKLIST**

**3-6 MONTHS BEFORE** (if applicable)
- [ ] Define event goals and KPIs
- [ ] Set budget
- [ ] Choose date and time
- [ ] Book venue
- [ ] Create event team/assign roles
- [ ] Start speaker/entertainment outreach
- [ ] Create event website/landing page

**2-3 MONTHS BEFORE**
- [ ] Finalize venue contract
- [ ] Book caterer
- [ ] Confirm speakers/entertainment
- [ ] Design marketing materials
- [ ] Set up registration system
- [ ] Order supplies/swag
- [ ] Arrange AV equipment
- [ ] Plan event schedule/agenda

**1 MONTH BEFORE**
- [ ] Send invitations/announcements
- [ ] Confirm vendor contracts
- [ ] Create run-of-show document
- [ ] Assign volunteer/staff roles
- [ ] Test registration system
- [ ] Order signage
- [ ] Plan social media campaign
- [ ] Arrange parking/transportation

**2 WEEKS BEFORE**
- [ ] Send reminder emails
- [ ] Confirm final headcount with caterer
- [ ] Print materials (programs, name tags, etc.)
- [ ] Create attendee list
- [ ] Test AV equipment
- [ ] Prepare presenter materials
- [ ] Confirm vendor arrival times
- [ ] Create emergency contact list

**1 WEEK BEFORE**
- [ ] Final walkthrough of venue
- [ ] Confirm all vendor deliveries
- [ ] Prepare registration desk materials
- [ ] Test all technology
- [ ] Brief all staff/volunteers
- [ ] Prepare welcome bags/swag
- [ ] Create seating chart (if needed)
- [ ] Charge all devices

**DAY BEFORE**
- [ ] Venue setup
- [ ] Decor installation
- [ ] AV setup and testing
- [ ] Registration desk setup
- [ ] Signage placement
- [ ] Final vendor confirmations
- [ ] Prepare day-of timeline
- [ ] Charge phone/devices

**EVENT DAY** 🎉

**Setup (X hours before)**
- [ ] Arrive early
- [ ] Final venue check
- [ ] Set up registration
- [ ] Test all tech one more time
- [ ] Brief team on roles
- [ ] Prepare welcome area

**During Event**
- [ ] Welcome attendees
- [ ] Manage registration
- [ ] Stick to schedule
- [ ] Handle issues as they arise
- [ ] Take photos/videos
- [ ] Collect feedback
- [ ] Monitor social media

**Breakdown**
- [ ] Thank speakers/vendors
- [ ] Collect materials
- [ ] Venue cleanup
- [ ] Return rented items
- [ ] Secure valuables

**POST-EVENT** (1 week after)
- [ ] Send thank you emails
- [ ] Process feedback surveys
- [ ] Pay final invoices
- [ ] Share photos/highlights
- [ ] Write post-event report
- [ ] Calculate ROI
- [ ] Document lessons learned
- [ ] Update contact database

**VENDOR CONTACTS**
| Vendor | Contact | Phone | Email | Arrival Time |
|--------|---------|-------|-------|--------------|
| Venue  | [Name]  | [#]   | [@]   | [Time]       |
| Caterer| [Name]  | [#]   | [@]   | [Time]       |

**BUDGET TRACKER**
| Item | Estimated | Actual | Variance |
|------|-----------|--------|----------|
| Venue| $X        | $X     | $X       |
| Food | $X        | $X     | $X       |
| **Total** | $X   | $X     | $X       |

**EMERGENCY CONTACTS**
- Venue manager: [Phone]
- Caterer: [Phone]
- AV tech: [Phone]
- Security: [Phone]
- Your team: [Phones]

**CONTINGENCY PLANS**
- Bad weather: [Plan B]
- Speaker cancellation: [Backup]
- Tech failure: [Backup equipment]
- Low attendance: [Adjustments]`
  },
